[window]

opacity = 0.6

[colors.primary]
background = '#282421'
foreground = '#EBD1B7'

[colors.cursor]
text = '#443e37'
cursor = '#f8f8f0'

[colors.normal]
black = '#443E37'
red = '#BA0E2E'
green = '#95cc5e'
yellow = '#db784d'
blue = '#60a365'
magenta = '#db784d'
cyan = '#95cc5e'
white = '#f1decb'

[colors.bright]
black = '#6e645a'
red = '#f03e5f'
green = '#c8e5ab'
yellow = '#ecb8a2'
blue = '#a1c8a4'
magenta = '#ecb8a2'
cyan = '#c8e5ab'
white = '#ffffff'

[font]

normal = { family = "Hack Nerd Font", style = "Regular"}
bold = { family = "Hack Nerd Font", style = "Bold"}
italic = { family = "Hack Nerd Font", style = "Italic"}
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic"}
