format = """
$directory $conda $git_branch
$character
"""

[conda]
ignore_base=false
symbol = "󱔎 "
style ="bg:blue fg:foreground"
format = "[](fg:blue)[$symbol$environment]($style)[](fg:blue)"

[directory]
style = "bg:yellow fg:foreground"
home_symbol = " "
format = "[](fg:yellow bg:yellow)[  $symbol$path]($style)[](fg:yellow)"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bg:green fg:foreground"
format = "[](fg:green)[$symbol$branch]($style)[](fg:green)"

[character]
success_symbol = "[➜](bold yellow) "
error_symbol = "[➜](bold red) "

